# commit to be tagged for the new release
commit = "HEAD"

project_name = "talos-rpi-kernel"
github_repo = "skyssolutions/talos-rpi-kernel"
match_deps = "^github.com/(skyssolutions/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
